### ISSUE TITLE
[Bug]: Annoying notifications every time I switch to another application

### ISSUE THREAD

**Issue by r00ta** [snapcrafters/mattermost-desktop#140]
### What happened?

MM is sending notifications every time I switch to another application with `ALT + TAB`. See the video in the attachments

### What should have happened?

MM should not send notification when I switch application. 

https://github.com/user-attachments/assets/1b9ba9a6-87e4-402d-a59e-a78bb3b74fd7

### Output of `snap info $snap_name`

```shell
$ snap info mattermost-desktop 
name:      mattermost-desktop
summary:   A secure, flexible platform build for the new era of collaboration
publisher: Snapcrafters✪
store-url: https://snapcraft.io/mattermost-desktop
contact:   https://github.com/snapcrafters/mattermost-desktop/issues
license:   MIT
description: |
  Mattermost is secure workplace messaging from behind your firewall.
  
  - Discuss topics in private groups, one-to-one or team-wide
  - Easily share and view image files
  - Connect in-house systems with webhooks and Slack-compatible integrations
  
  For technical and operations teams who execute high-stakes, collaborative
  workflows,
  Mattermost provides integrated team messaging, audio and screen share,
  workflow automation
  and project management. Governments, banks and tech giants use our secure
  collaboration platform
  to reduce risk and error rates while accelerating technical productivity.
  
  To use this app, you need a URL for a Mattermost server.
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - mattermost-desktop
snap-id:      ed0pxJoDHrgmAWHH7baX5nryAHy1UNj0
tracking:     latest/stable
refresh-date: 5 days ago, at 13:10 CEST
channels:
  latest/stable:    5.13.1 2025-09-19 (800) 130MB -
  latest/candidate: 5.13.1 2025-09-19 (800) 130MB -
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          5.13.1            (800) 130MB -
```

### Output of `snap connections $snap_name`

```shell
$ snap connections mattermost-desktop
Interface               Plug                                       Slot                            Notes
audio-playback          mattermost-desktop:audio-playback          :audio-playback                 -
audio-record            mattermost-desktop:audio-record            -                               -
camera                  mattermost-desktop:camera                  -                               -
content[gnome-46-2404]  mattermost-desktop:gnome-46-2404           gnome-46-2404:gnome-46-2404     -
content[gpu-2404]       mattermost-desktop:gpu-2404                mesa-2404:gpu-2404              -
content[gtk-3-themes]   mattermost-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    mattermost-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   mattermost-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 mattermost-desktop:desktop                 :desktop                        -
desktop-legacy          mattermost-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               mattermost-desktop:gsettings               :gsettings                      -
home                    mattermost-desktop:home                    :home                           -
login-session-observe   mattermost-desktop:login-session-observe   -                               -
network                 mattermost-desktop:network                 :network                        -
network-bind            mattermost-desktop:network-bind            :network-bind                   -
opengl                  mattermost-desktop:opengl                  :opengl                         -
pulseaudio              mattermost-desktop:pulseaudio              :pulseaudio                     -
removable-media         mattermost-desktop:removable-media         -                               -
screen-inhibit-control  mattermost-desktop:screen-inhibit-control  :screen-inhibit-control         -
shared-memory           mattermost-desktop:shmem                   :shared-memory                  -
unity7                  mattermost-desktop:unity7                  :unity7                         -
wayland                 mattermost-desktop:wayland                 :wayland                        -
x11                     mattermost-desktop:x11                     :x11                            -
```

### Output of `snap version`

```shell
$ snap version
snap    2.71
snapd   2.71
series  16
ubuntu  22.04
kernel  5.17.0-1032-oem
```

### Relevant log output

```shell

```

### Teminal output of app

```shell

```

**Comment by wctaylor** [comment]
I have been having the same issue since September 19, 2025, so I think it is related to enabling Wayland or to [this commit](https://github.com/snapcrafters/mattermost-desktop/commit/d7adaa6f13a4d7ed5984af8eeff44d86fe997a9b).

Oddly enough, it does NOT happen to me if I Alt + Tab away from Mattermost or if I click on a different window, but it DOES happen if I click any application icon in the dock.

**Comment by jnsgruk** [comment]
Hey. I pushed a new revision to candidate to see if I could fix this - can you check it out over at: https://github.com/snapcrafters/mattermost-desktop/issues/141

Or just `sudo snap refresh mattermost-desktop --channel latest/candidate` 🙂

**Comment by wctaylor** [comment]
I just refreshed to the candidate release, and I still get the notifications when clicking away to other icons in the dock. Seems like it must be related to the Wayland changes then

**Comment by jnsgruk** [comment]
@kenvandine any ideas what might be causing this?

**Comment by wctaylor** [comment]
For what it's worth, I'm running Ubuntu 24.04.3 with GNOME 46 (as provisioned by Canonical's corporate `autoinstall.yaml`)

**Comment by kenvandine** [comment]
> [@kenvandine](https://github.com/kenvandine) any ideas what might be causing this?

That notification is GNOME's focus-stealing prevention, which can be really annoying. The goal here is to prevent an application from raising focus while you are typing and stealing your input. The odd thing is GNOME thinks Mattermost is trying to request focus. I haven't been able to reproduce this behavior myself.

**Comment by peetCreative** [comment]
Having the same problem here. Did anyone tried on a more recent version of Ubuntu?

**Comment by skatsaounis** [comment]
I face a similar bug on Jammy with mattermost-desktop 5.13.2 (rev 804) from latest/stable. If I click a Gnome notification of Mattermost itself, e.g., a notification for a message I just received, then the annoying notification `"Mattermost Desktop App" is ready` is triggered.

**Comment by jnsgruk** [comment]
@kenvandine and I did some troubleshooting on this today, and it seems to be related to the recent changes to the snap which enabled wayland support by default.

We'll revert that today, and continue to work out why that would be the case before re-releasing. You should see the snap update automatically and solve the problem automatically in a few hours.

**Comment by arif-ali** [comment]
> I face a similar bug on Jammy with mattermost-desktop 5.13.2 (rev 804) from latest/stable. If I click a Gnome notification of Mattermost itself, e.g., a notification for a message I just received, then the annoying notification `"Mattermost Desktop App" is ready` is triggered.

I see this, but that just makes me click it, and MM pops up.

I guess, ideally, it should just open the MM window. But it doesn't bother me too much, and didn't really feel the annoyance there personally.

I'll pop over to candidate, and see if we have the same issue

btw, I run questing, so no choice but to have Wayland

**Comment by arif-ali** [comment]
confirmed that revision 806 is good

**Comment by jnsgruk** [comment]
The revision that solves this issue is now in ‘latest/stable’
